name: publish-docker-image-on-branch

on:
  push:
    branches:
      - master
      - develop

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: ${{ secrets.DOCKER_USERNAME }}/tokenbridge-contracts
          always_pull: true
          tags: ${GITHUB_REF#refs/heads/}-${GITHUB_SHA::8}
